name: OpenEMR Test Suite

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/run-suite.yml
    with:
      scope: full
